# Generated by Django 4.2.2 on 2023-09-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
