# Generated by Django 4.2.2 on 2023-09-18 13:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_secondfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fastfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='food')),
                ('about', ckeditor.fields.RichTextField()),
                ('ingredient', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
